//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR.BinPacking.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PRE_ScaleElements {
            get {
                return ((bool)(this["PRE_ScaleElements"]));
            }
            set {
                this["PRE_ScaleElements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PRE_ExpandPreviewInPresentation {
            get {
                return ((bool)(this["PRE_ExpandPreviewInPresentation"]));
            }
            set {
                this["PRE_ExpandPreviewInPresentation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PRE_ExpandPreviewInResult {
            get {
                return ((bool)(this["PRE_ExpandPreviewInResult"]));
            }
            set {
                this["PRE_ExpandPreviewInResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simple")]
        public global::MR.BinPacking.App.Utils.FileType LastFileType {
            get {
                return ((global::MR.BinPacking.App.Utils.FileType)(this["LastFileType"]));
            }
            set {
                this["LastFileType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastFileHeaderType {
            get {
                return ((int)(this["LastFileHeaderType"]));
            }
            set {
                this["LastFileHeaderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string LastFileBinSize {
            get {
                return ((string)(this["LastFileBinSize"]));
            }
            set {
                this["LastFileBinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string VIS_BinSize {
            get {
                return ((string)(this["VIS_BinSize"]));
            }
            set {
                this["VIS_BinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string VIS_MinValue {
            get {
                return ((string)(this["VIS_MinValue"]));
            }
            set {
                this["VIS_MinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string VIS_MaxValue {
            get {
                return ((string)(this["VIS_MaxValue"]));
            }
            set {
                this["VIS_MaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string VIS_ElementsCount {
            get {
                return ((string)(this["VIS_ElementsCount"]));
            }
            set {
                this["VIS_ElementsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,3333")]
        public string VIS_AASEpsilon {
            get {
                return ((string)(this["VIS_AASEpsilon"]));
            }
            set {
                this["VIS_AASEpsilon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VIS_IsCheckedNF {
            get {
                return ((bool)(this["VIS_IsCheckedNF"]));
            }
            set {
                this["VIS_IsCheckedNF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedFF {
            get {
                return ((bool)(this["VIS_IsCheckedFF"]));
            }
            set {
                this["VIS_IsCheckedFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedBF {
            get {
                return ((bool)(this["VIS_IsCheckedBF"]));
            }
            set {
                this["VIS_IsCheckedBF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedFFD {
            get {
                return ((bool)(this["VIS_IsCheckedFFD"]));
            }
            set {
                this["VIS_IsCheckedFFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedBFD {
            get {
                return ((bool)(this["VIS_IsCheckedBFD"]));
            }
            set {
                this["VIS_IsCheckedBFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedRF {
            get {
                return ((bool)(this["VIS_IsCheckedRF"]));
            }
            set {
                this["VIS_IsCheckedRF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedAAS {
            get {
                return ((bool)(this["VIS_IsCheckedAAS"]));
            }
            set {
                this["VIS_IsCheckedAAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedReduction {
            get {
                return ((bool)(this["VIS_IsCheckedReduction"]));
            }
            set {
                this["VIS_IsCheckedReduction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedExact {
            get {
                return ((bool)(this["VIS_IsCheckedExact"]));
            }
            set {
                this["VIS_IsCheckedExact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIS_IsCheckedMetaheuristic {
            get {
                return ((bool)(this["VIS_IsCheckedMetaheuristic"]));
            }
            set {
                this["VIS_IsCheckedMetaheuristic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string EXP_From {
            get {
                return ((string)(this["EXP_From"]));
            }
            set {
                this["EXP_From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string EXP_To {
            get {
                return ((string)(this["EXP_To"]));
            }
            set {
                this["EXP_To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string EXP_Step {
            get {
                return ((string)(this["EXP_Step"]));
            }
            set {
                this["EXP_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string EXP_Repeat {
            get {
                return ((string)(this["EXP_Repeat"]));
            }
            set {
                this["EXP_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string EXP_BinSize {
            get {
                return ((string)(this["EXP_BinSize"]));
            }
            set {
                this["EXP_BinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,01")]
        public string EXP_MinValue {
            get {
                return ((string)(this["EXP_MinValue"]));
            }
            set {
                this["EXP_MinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string EXP_MaxValue {
            get {
                return ((string)(this["EXP_MaxValue"]));
            }
            set {
                this["EXP_MaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EXP_IsCheckedDistUniform {
            get {
                return ((bool)(this["EXP_IsCheckedDistUniform"]));
            }
            set {
                this["EXP_IsCheckedDistUniform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedDistGauss {
            get {
                return ((bool)(this["EXP_IsCheckedDistGauss"]));
            }
            set {
                this["EXP_IsCheckedDistGauss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedDistExponential {
            get {
                return ((bool)(this["EXP_IsCheckedDistExponential"]));
            }
            set {
                this["EXP_IsCheckedDistExponential"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EXP_IsCheckedSortNone {
            get {
                return ((bool)(this["EXP_IsCheckedSortNone"]));
            }
            set {
                this["EXP_IsCheckedSortNone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedSortAscending {
            get {
                return ((bool)(this["EXP_IsCheckedSortAscending"]));
            }
            set {
                this["EXP_IsCheckedSortAscending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedSortDescending {
            get {
                return ((bool)(this["EXP_IsCheckedSortDescending"]));
            }
            set {
                this["EXP_IsCheckedSortDescending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,3333")]
        public string EXP_AASEpsilon {
            get {
                return ((string)(this["EXP_AASEpsilon"]));
            }
            set {
                this["EXP_AASEpsilon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedNF {
            get {
                return ((bool)(this["EXP_IsCheckedNF"]));
            }
            set {
                this["EXP_IsCheckedNF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedFF {
            get {
                return ((bool)(this["EXP_IsCheckedFF"]));
            }
            set {
                this["EXP_IsCheckedFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedBF {
            get {
                return ((bool)(this["EXP_IsCheckedBF"]));
            }
            set {
                this["EXP_IsCheckedBF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedFFD {
            get {
                return ((bool)(this["EXP_IsCheckedFFD"]));
            }
            set {
                this["EXP_IsCheckedFFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedBFD {
            get {
                return ((bool)(this["EXP_IsCheckedBFD"]));
            }
            set {
                this["EXP_IsCheckedBFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedRF {
            get {
                return ((bool)(this["EXP_IsCheckedRF"]));
            }
            set {
                this["EXP_IsCheckedRF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedAAS {
            get {
                return ((bool)(this["EXP_IsCheckedAAS"]));
            }
            set {
                this["EXP_IsCheckedAAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedReduction {
            get {
                return ((bool)(this["EXP_IsCheckedReduction"]));
            }
            set {
                this["EXP_IsCheckedReduction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedExact {
            get {
                return ((bool)(this["EXP_IsCheckedExact"]));
            }
            set {
                this["EXP_IsCheckedExact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXP_IsCheckedMetaheuristic {
            get {
                return ((bool)(this["EXP_IsCheckedMetaheuristic"]));
            }
            set {
                this["EXP_IsCheckedMetaheuristic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PRE_ExpandSideBarInPresentation {
            get {
                return ((bool)(this["PRE_ExpandSideBarInPresentation"]));
            }
            set {
                this["PRE_ExpandSideBarInPresentation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PRE_ExpandSideBarInResult {
            get {
                return ((bool)(this["PRE_ExpandSideBarInResult"]));
            }
            set {
                this["PRE_ExpandSideBarInResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double PRE_BinsElementsMargin {
            get {
                return ((double)(this["PRE_BinsElementsMargin"]));
            }
            set {
                this["PRE_BinsElementsMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double PRE_BinsElementsMinWidth {
            get {
                return ((double)(this["PRE_BinsElementsMinWidth"]));
            }
            set {
                this["PRE_BinsElementsMinWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double PRE_BinsElementsBorderThickness {
            get {
                return ((double)(this["PRE_BinsElementsBorderThickness"]));
            }
            set {
                this["PRE_BinsElementsBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFBFBFBF")]
        public global::System.Windows.Media.Color PRE_BinsFillColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PRE_BinsFillColor"]));
            }
            set {
                this["PRE_BinsFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color PRE_BinsFontColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PRE_BinsFontColor"]));
            }
            set {
                this["PRE_BinsFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color PRE_BinsElementsBorderColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PRE_BinsElementsBorderColor"]));
            }
            set {
                this["PRE_BinsElementsBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color PRE_ElementsFillColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PRE_ElementsFillColor"]));
            }
            set {
                this["PRE_ElementsFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color PRE_ElementsFontColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PRE_ElementsFontColor"]));
            }
            set {
                this["PRE_ElementsFontColor"] = value;
            }
        }
    }
}
